trigger:
  branches:
    include:
      - main
  paths:
    include:
    - study_project/*
pool:
  vmImage: ubuntu-latest

steps:

- bash: 
    git clone https://oauth2:$GITHUB_TOKEN@github.com/doug2901/Terraform.git
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Cloning repo'

- script: |
    cd Terraform/study_project/
    terraform init
    terraform plan -out=tfPlan
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
  displayName: 'Initializing & planning Terraform'
- task: ManualValidation@0
  timeoutInMinutes: 1440 # task times out in 1 day
  inputs:
    notifyUsers: 'douglas@dnfcorp.com.br'
    instructions: 'Plase check the pipeline'
    onTimeout: 'reject'
- script: |
    terraform apply