trigger:
  branches:
    include:
      - main
  paths:
    include:
    - study_project/*
pool:
  vmImage: ubuntu-latest

steps:
- bash: 
    terraform -version
  displayName: 'Terraform-Configuration'

- bash:
    cd $(System.DefaultWorkingDirectory)/study_project
    ls