trigger:
  branches:
    include:
      - main
  paths:
    include:
    - study_project/*
pool:
  vmImage: ubuntu-latest

steps:
- bash: 
    git clone https://oauth2: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@github.com/doug2901/Terraform.git
- bash: 
    terraform -version
  displayName: 'Terraform-Configuration'