trigger:
- main
pool:
  vmImage: ubuntu-latest

steps:
- bash: 
    terraform -version
  displayName: 'Terraform-Configuration'

- bash:
    cd $(System.DefaultWorkingDirectory)/Terraform/study_project
    ls