trigger:
  branches:
    include:
      - main
  paths:
    include:
    - study_project/*
pool:
  vmImage: ubuntu-latest

steps:

- bash: 
    git clone https://oauth2:$GITHUB_TOKEN@github.com/doug2901/Terraform.git
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
- bash: 
    cd Terraform/study_project/ && ls -ltr
- bash: 
    terraform -version
  displayName: 'Terraform-Configuration'