name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pre-prod
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls files
        run: ls -ltr

      - name: Instalar Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"  # ou sua versão preferida

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save plan to file
        run: terraform show -no-color tfplan > plan.txt

      - name: Send plan via email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587 
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Terraform Plan - ${{ github.repository }}"
          to: ${{ secrets.SMTP_USER }}
          from: "Terraform Bot <${{ secrets.SMTP_USER }}>"
          body: |
            Segue abaixo o resultado do Terraform Plan:
            
            ${{ github.run_id }}

          attachments: plan.txt