name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pre-prod
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls files
        run: ls -ltr

      - name: Instalar Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"  # ou sua versão preferida

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out=tfplan || export exitcode=$?
        continue-on-error: true # Allow the step to continue even if -detailed-exitcode returns 2

      - name: Check Plan Exit Code
        if: steps.plan.outcome == 'success' && steps.plan.outputs.exitcode == '2'
        run: |
          echo "Terraform plan detected changes. Proceeding with apply (or manual approval)."
          # Add logic for manual approval or direct apply here

      - name: No Changes Detected
        if: steps.plan.outcome == 'success' && steps.plan.outputs.exitcode == '0'
        run: |
          echo "No changes detected by Terraform plan. Skipping apply."

      - name: Terraform Plan Failed
        if: steps.plan.outcome == 'failure' || steps.plan.outputs.exitcode == '1'
        run: |
          echo "Terraform plan failed. Review the logs for errors."
          exit 1 # Fail the workflow

      - name: Send plan via email
        if: steps.plan.outcome == 'success' && steps.plan.outputs.exitcode == '2'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587 
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Terraform Plan - ${{ github.repository }}"
          to: ${{ secrets.SMTP_USER }}
          from: "Terraform Bot <${{ secrets.SMTP_USER }}>"
          body: |
            Foram detectadas alterações no Terraform.  
            Segue o diff abaixo:

            ${{ steps.plan.outputs.stdout }}