name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pre-prod
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls files
        run: ls -ltr

      - name: Instalar Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"  # ou sua versão preferida

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          set -e
          if [ $exit_code -eq 2 ]; then
            echo "There are pending changes."
            exit 0
          elif [ $exit_code -eq 0 ]; then
            echo "No changes detected in the Terraform plan."
            exit 0
          else
            echo "Terraform plan failed."
            exit 1
          fi

      - name: Send plan via email
        if: steps.plan.outputs.exit_code == '2'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587 
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Terraform Plan - ${{ github.repository }}"
          to: ${{ secrets.SMTP_USER }}
          from: "Terraform Bot <${{ secrets.SMTP_USER }}>"
          body: |
            Foram detectadas alterações no Terraform.  
            Segue o diff abaixo:

            ${{ steps.plan.outputs.stdout }}