name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls files
        run: ls -ltr

      - name: Instalar Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"  # ou sua versão preferida

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main'
#        run: terraform apply -auto-approve tfplan